version: "3"
services:
  mariadb:
    image: 'docker.io/bitnami/mariadb:10.3-debian-10'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
    volumes:
      - '${DATA_PATH_HOST}:/bitnami/mariadb'
  joomla:
    image: 'docker.io/bitnami/joomla:3-debian-10'
    ports:
      - '${JOOMLA_HTTP_PORT}:8080'
      - '${JOOMLA_HTTPS_PORT}:8443'
    environment:
      - JOOMLA_DATABASE_HOST=mariadb
      - JOOMLA_DATABASE_PORT_NUMBER=3306
      - JOOMLA_DATABASE_USER=${MARIADB_USER}
      - JOOMLA_DATABASE_NAME=${MARIADB_DATABASE}
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - '${APP_CODE_PATH_HOST}:/bitnami/joomla'
    depends_on:
      - mariadb
volumes: {}
