version: "3"
services:
  mariadb:
    build: 
      context: './mariadb'
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
      - 'MARIADB_USER=${DB_USER}'
      - 'MARIADB_DATABASE=${DB_NAME}'
    volumes:
      - '${DATA_PATH_HOST}:/bitnami/mariadb'
  joomla:
    build: 
      context: './joomla'
    ports:
      - '${JOOMLA_HTTP_PORT}:8080'
      - '${JOOMLA_HTTPS_PORT}:8443'
    environment:
      - 'JOOMLA_DATABASE_HOST=mariadb'
      - 'JOOMLA_DATABASE_PORT_NUMBER=3306'
      - 'JOOMLA_DATABASE_USER=${DB_USER}'
      - 'JOOMLA_DATABASE_NAME=${DB_NAME}'
      - 'ALLOW_EMPTY_PASSWORD=yes'
    volumes:
      - '${APP_CODE_PATH_HOST}:/bitnami/joomla'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  joomla_data:
    driver: local
