name: "Release"

on:
  push:
    branches: [ master ]
env:
  IMAGE_NAME: joomla
  VERSION: v4.0.6
jobs:
  buildImage:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@master
        with:
          platforms: linux/amd64,linux/arm64,linux/ppc64le,linux/s390x

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
        with:
          driver-opts: image=moby/buildkit:master
      
      - name: log into GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN}}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

      - uses: actions/checkout@v2
      - name: Build Container image Backend nginx php 8.0
        run: docker buildx build --platform linux/amd64,linux/arm64,linux/ppc64le,linux/s390x --build-arg PHP_VERSION="8.0",BACK_END=nginx,DISPLAY=on,XDEBUG=true --file ./nginx/Dockerfile-8.0 --tag ghcr.io/deck-app/joomla4.0.6
      - name: Build Container image Backend nginx php 7.4
        run: docker buildx build --platform linux/amd64,linux/arm64,linux/ppc64le,linux/s390x --build-arg PHP_VERSION=7.4,BACK_END=nginx,DISPLAY=on,XDEBUG=true --tag ghcr.io/deck-app/joomla4.0.6 nginx/Dockerfile-7.4
      - name: Build Container image Backend apache php 8.0
        run: docker buildx build --platform linux/amd64,linux/arm64,linux/ppc64le,linux/s390x --build-arg PHP_VERSION="8.0",BACK_END=apache,DISPLAY=on,XDEBUG=true --tag ghcr.io/deck-app/joomla4.0.6 apache/Dockerfile-8.0
      - name: Build Container image Backend apache php 7.4
        run: docker buildx build --platform linux/amd64,linux/arm64,linux/ppc64le,linux/s390x --build-arg PHP_VERSION=7.4,BACK_END=apache,DISPLAY=on,XDEBUG=true --tag ghcr.io/deck-app/joomla4.0.6 apache/Dockerfile-7.4
